#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

if defined? Maglev
Exception.install_debug_block do |e|
  msg = e.instance_variable_get(:@_st_messageText)
  case e.class.name
    #when 'RubyThrowException', 'Errno::ENOENT', 'LoadError', 'RubyBreakException'
      #ignore
    when 'NameError'
      #m = Maglev::PERSISTENT_ROOT
      # nil.pause if msg =~ /Group is not missing constant/
    else
    #ignore
      #puts "-- #{e}    (#{e.class.name})"
  end
end
end

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
